robot_base_frame: $(arg robot_base_frame)

obstacle_range: 2.5
raytrace_range: 3.0
# footprint: [[0.419, 0.319], [-1.272, 0.672], [-1.272, -0.672], [0.419, -0.319]]
# footprint: [[0.419, 0.319], [-0.419, 0.319], [-0.419, -0.319], [0.419, -0.319]]

observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: $(arg robot_name)/front_lidar_link
  topic: front_lidar/scan
  data_type: LaserScan
  marking: true
  clearing: true
  inf_is_valid: true