local_costmap:
  global_frame: $(arg odom_frame)
  inflation_radius: 0.2
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05
