odom0          : diff_drive_controller/odom
imu0           : imu/data
base_link_frame: $(arg robot_base_frame)
odom_frame     : $(arg odom_frame)
map_frame      : $(arg map_frame)
world_frame    : $(arg odom_frame)

frequency: 30
sensor_timeout: 0.1
two_d_mode: true
transform_time_offset: 0.0
transform_timeout: 0.0
print_diagnostics: true
publish_tf: true
publish_acceleration: false

odom0_config: [false, false, false,
               false, false, false,
               true, false, false,
               false, false, true,
               false, false, false]

imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]
