diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : "agv_left_wheel_joint"
  right_wheel : "agv_right_wheel_joint"
  enable_odom_tf : $(arg enable_odom_tf)
  base_frame_id  : $(arg robot_name)/base_link
  odom_frame_id  : $(arg robot_name)/odom
  publish_rate     : 50
  wheel_separation : 0.44
  wheel_radius     : 0.065
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]