TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.1
  acc_lim_theta: 0.3
  acc_lim_x: 0.3

  yaw_goal_tolerance: 0.05 # default: 0.05[rad]
  xy_goal_tolerance: 0.10 # default: 0.10[m]

  meter_scoring: true # default: false
  path_distance_bias: 1.0
  holonomic_robot: false

TebLocalPlannerROS:
  odom_topic: ekf_localization/odom
  map_frame : $(arg robot_name)/odom

  max_vel_x: 0.5
  max_vel_x_backwards: 0.5
  max_vel_theta: 0.5
  acc_lim_theta: 0.3
  acc_lim_x: 0.3

  footprint_model:
    type: polygon
    vertices: [[0.419, 0.319], [-0.419, 0.319], [-0.419, -0.319], [0.419, -0.319]]

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05

  global_plan_overwrite_orientation: false # default: true

  min_obstacle_dist: 0.2

TowableLocalPlanner:
  acc_lim_x: 1.0
  acc_lim_theta: 2.0
  max_vel_x: 0.1
  min_vel_x: 0.1
  max_vel_x_backwards: 0.1
  max_vel_theta: 0.6
  min_in_place_vel_theta: 0.3

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10
  latch_xy_goal_tolerance: true

  distance_error_weight: 1.0
  yaw_error_weight: 2.0
  rot_vel_weight: 0.5
  rot_vel_var_weight: 0.5
  prediction_horizon: 3.0

  towing: false