base_global_planner: global_planner/GlobalPlanner
# base_local_planner : teb_local_planner/TebLocalPlannerROS
base_local_planner: towable_local_planner/TowableLocalPlanner

planner_frequency   : 0.0  # default: 0.0
planner_patience    : 5.0  # default: 5.0
controller_frequency: 20.0 # default: 20.0
controller_patience : 15.0 # default: 15.0